name: app_flutter_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.5
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.1
  fake_async: ^1.3.3
  mocktail_image_network: ^1.2.0

flutter:
  uses-material-design: true
